### PR TITLE
androidx migration: Resolved conflicts and added more androidx migrations

### PR DESCRIPTION
**Pull request by alashow**

### CODE REVIEW

**Comment by alashow** [comment]
Hey @elihart @jeffreydelooff, could you please help me with fixing some of the tests?
Currently, tests of `epoxy-modelfactory` are failing.

Gradle scan: https://scans.gradle.com/s/2c5p3vm4p3fs6
Diff of `BasicModelWithAttribute_` in tests: https://www.diffchecker.com/ILbgE4ts

**Comment by elihart** [comment]
@ngsilverman do you know why `epoxy-modelfactory` tests are failing?

**Comment by alashow** [comment]
BTW, I run `./gradlew aR` to get aar's and jar's, then I added them to my project and it compiled.
Although I had to add java-poet and kotlin-poet too.
```
kapt files('libs/epoxy-processor-3.0.0-SNAPSHOT.jar')
implementation files('libs/epoxy-annotations-3.0.0-SNAPSHOT.jar')
implementation files('libs/epoxy-adapter-release.aar')
implementation files('libs/epoxy-paging-release.aar')
implementation files('libs/epoxy-databinding-release.aar')
implementation "com.squareup:javapoet:1.10.0"
implementation "com.squareup:kotlinpoet:0.7.0"
```

**Comment by ngsilverman** [comment]
@elihart @alashow I'm rather confused. The "Expected source" in the test error page does not match the test resource, which correctly includes the `from(ModelProperties ...)` method: https://github.com/airbnb/epoxy/blob/master/epoxy-modelfactory/src/test/resources/BasicModelWithAttribute_.java

**Comment by alashow** [comment]
I checked, it's actually testing against `BasicModelWithAttribute_.java` located in [epoxy-processortest](https://github.com/airbnb/epoxy/blob/master/epoxy-processortest/src/test/resources/BasicModelWithAttribute_.java). When I added `from(ModelProperties ...)` method to it, it succeeded.

**Comment by alashow** [comment]
Also, `allTypesModelView` [test throws](https://scans.gradle.com/s/2c5p3vm4p3fs6/tests/3qb3w24w2oha6-pbejgwr2b2ofo?openStackTraces=WzBd) not found exception because `epoxy-modelfactory` has  `AllTypesModelView_.java` but `epoxy-processortest` doesn't.

**Comment by alashow** [comment]
I run `cp  epoxy-modelfactory/src/test/resources/* epoxy-processortest/src/test/resources` to see what happens, and now only 3 tests are failing.
https://scans.gradle.com/s/nrp6tbwhz4s76/tests/3qb3w24w2oha6-lwipvceka3mbi

**Comment by ngsilverman** [comment]
@alashow that should not be necessary. The `from(ModelProperties ...)` methods should only be generated when `epoxy-modelfactory` is a dependency and `epoxy-processortest` doesn't depend on it.

However `epoxy-modelfactory` does depend on `epoxy-processortest` so perhaps the resource of the former are being overridden by the later due to this change? You could try renaming the resources so that there's no conflict.

**Comment by alashow** [comment]
That doesn't explain why tests don't fail on `master` branch. Still, I tried renaming them and it still didn't work. 
Could you please clone this branch and see what's wrong with it?

**Comment by jeffreydelooff** [comment]
Why was this closed? What's the status?

**Comment by alashow** [comment]
Status: only [those](https://github.com/jeffreydelooff/epoxy/pull/1#issuecomment-411271468) tests are not succeeding.
I wasted too much time trying to fix them. I even tried to migrate it from scratch, but there were more test fails related to DataBinding and other unrelated errors.
So I gave up :) Hence the closing. Waiting for someone to pick this up. Until then AAR's build with `./gradlew aR` works for me without issues.

**Pull request closed without merging**
